### ISSUE TITLE
With lazy module

### ISSUE THREAD

**Issue by geisimarrech87** [puskaspeti/pp-breadcrumbs#1]
Hello.
Today my project has several modules with specific route files.

I can not get the crumb when I use lazy module.

Is there any way to do this in the component?

**Comment by puskaspeti** [comment]
Hi,
did you import the PpBreadcrumbsModule in the lazy modules as well?

**Comment by geisimarrech87** [comment]
> Hi,
> did you import the PpBreadcrumbsModule in the lazy modules as well?


I import into a shared module

**Comment by puskaspeti** [comment]
Does the SharedModule export the PpBreadcrumbsModule?

**Comment by geisimarrech87** [comment]
> O SharedModule exporta o PpBreadcrumbsModule?

Yes

**Comment by puskaspeti** [comment]
I've created a working lazy module demo with a shared module, you can check out on [StackBlitz](https://stackblitz.com/edit/pp-breadcrumbs) (open in Firefox for example, StackBlitz is not working properly in Chrome at the moment)

**Comment by geisimarrech87** [comment]
Thank you very much!

The code that was in app.component was missing.
